### ISSUE TITLE
Windows errors

### ISSUE THREAD

**Issue by sonicviz** [taskandtool/saas-starter#10]
Hi,
Looks like an interesting project so I took a look at it.
Getting some errors on NPM Install and also running.

What would be the best and most efficient process to upgrade it to latest meteor / react?

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN react-addons-shallow-compare@15.3.2 requires a peer of react@^15.3.2 but none was installed.

G:\Meteor Projects\Project X\saas-starter-master>node dev.js
Building core-js@1.2.7 without ES6 number constructor...                 Hash: 4aaa9f6d5566d1819016
Version: webpack 1.13.2
Time: 3315ms
               Asset    Size  Chunks             Chunk Names
    server.bundle.js  190 kB       0  [emitted]  main
server.bundle.js.map  238 kB       0  [emitted]  main
chunk    {0} server.bundle.js, server.bundle.js.map (main) 17 51% 9/13 builHash: fe9d44c27501a54e9e02
Version: webpack 1.13.2
Time: 491ms
               Asset    Size  Chunks             Chunk Names
    server.bundle.js  190 kB       0  [emitted]  main
server.bundle.js.map  238 kB       0  [emitted]  main
chunk    {0} server.bundle.js, server.bundle.js.map (main) 179 kB [rendHash: df7d5599ec547851a4b5
Version: webpack 1.13.2
Time: 15055ms
           Asset    Size  Chunks             Chunk Names
client.bundle.js  3.2 MB       0  [emitted]  main
chunk    {0} client.bundle.js (main) 2.68 MB [rendered]
webpack: bundle is now VALID.
[[[[[ ~\G\Meteor Projects\Project X\saas-starter-master\meteor_core ]]]]]

=> Started proxy.
=> Meteor 1.4.1.3 is available. Update this project with 'meteor update'.
=> Started MongoDB.
=> Exited with code: 8
W20161024-16:57:39.438(9)? (STDERR) The regenerator/runtime module is deprecated; please import regenerator-runtime/runtime instead.
W20161024-16:57:39.441(9)? (STDERR)
W20161024-16:57:39.441(9)? (STDERR) C:\Users\Paul\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20161024-16:57:39.441(9)? (STDERR)                                             throw(ex);
W20161024-16:57:39.442(9)? (STDERR)                                                   ^
W20161024-16:57:39.442(9)? (STDERR) Error: Match error: Failed Match.Where validation in field region
W20161024-16:57:39.442(9)? (STDERR)     at check (meteor://�app/packages/check/match.js:33:1)
W20161024-16:57:39.442(9)? (STDERR)     at new Slingshot.Directive (meteor://�app/packages/edgee_slingshot/packages/edgee_slingshot.js:304:1)
W20161024-16:57:39.442(9)? (STDERR)     at Object.Slingshot.createDirective (meteor://�app/packages/edgee_slingshot/packages/edgee_slingshot.js:274:1)
W20161024-16:57:39.443(9)? (STDERR)     at Object.defineProperty.value (G:\Meteor Projects\Project X\saas-starter-master\webpack\assets\server.bundle.js:6023:12)
W20161024-16:57:39.443(9)? (STDERR)     at __webpack_require__ (G:\Meteor Projects\Project X\saas-starter-master\webpack\assets\server.bundle.js:26:30)
W20161024-16:57:39.443(9)? (STDERR)     at Object.defineProperty.value (G:\Meteor Projects\Project X\saas-starter-master\webpack\assets\server.bundle.js:5250:2)
W20161024-16:57:39.443(9)? (STDERR)     at __webpack_require__ (G:\Meteor Projects\Project X\saas-starter-master\webpack\assets\server.bundle.js:26:30)
W20161024-16:57:39.444(9)? (STDERR)     at Object.installedModules (G:\Meteor Projects\Project X\saas-starter-master\webpack\assets\server.bundle.js:58:19)
W20161024-16:57:39.444(9)? (STDERR)     at __webpack_require__ (G:\Meteor Projects\Project X\saas-starter-master\webpack\assets\server.bundle.js:26:30)
W20161024-16:57:39.444(9)? (STDERR)     at G:\Meteor Projects\Project X\saas-starter-master\webpack\assets\server.bundle.js:46:18
W20161024-16:57:39.444(9)? (STDERR)     at Object.<anonymous> (G:\Meteor Projects\Project X\saas-starter-master\webpack\assets\server.bundle.js:49:10)
W20161024-16:57:39.445(9)? (STDERR)     at Module._compile (module.js:456:26)
W20161024-16:57:39.445(9)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20161024-16:57:39.446(9)? (STDERR)     at Module.load (module.js:356:32)
W20161024-16:57:39.446(9)? (STDERR)     at Function.Module._load (module.js:312:12)
W20161024-16:57:39.446(9)? (STDERR)     at Module.require (module.js:364:17)

**Comment by sonicviz** [comment]
I ran https://www.npmjs.com/package/npm-check-updates if that helps determine the issues?

G:\Meteor Projects\Project X\saas-starter-master>ncu
Using G:\Meteor Projects\Project X\saas-starter-master\package.json
[..................] \ :
 blueimp-md5                       ^1.1.1  →          ^2.4.0
 history                          ^1.12.0  →          ^4.3.0
 lodash                           ^3.10.0  →         ^4.16.4
 react                            ^0.14.8  →         ^15.3.2
 react-dom                        ^0.14.0  →         ^15.3.2
 react-helmet                      ^1.1.5  →          ^3.1.0
 react-mailto                      ^0.3.0  →          ^0.4.0
 react-mixin                       ^2.0.1  →          ^3.0.5
 react-router                  ^1.0.0-rc3  →          ^2.8.1
 react-typeahead                   ^1.1.5  →  ^2.0.0-alpha.5
 babel                            ^5.8.21  →          ^6.5.2
 babel-core                       ^5.8.22  →         ^6.17.0
 babel-eslint                      ^4.0.5  →          ^7.0.0
 babel-loader                      ^5.1.2  →          ^6.2.5
 babel-plugin-react-transform      ^1.1.0  →          ^2.0.2
 core-js                           ^1.2.2  →          ^2.4.1
 css-loader                       ^0.15.3  →         ^0.25.0
 eslint-config-airbnb               0.0.7  →          12.0.0
 eslint-plugin-react               ^3.2.2  →          ^6.4.1
 karma                            ^0.13.9  →          ^1.3.0
 karma-chrome-launcher             ^0.2.0  →          ^2.0.0
 karma-jasmine                     ^0.2.2  →          ^1.0.2
 lost                              ^6.6.2  →          ^7.1.0
 node-libs-browser                 ^0.5.2  →          ^1.0.0
 postcss-loader                    ^0.6.0  →          ^1.0.0
 shelljs                           ^0.5.3  →          ^0.7.4
 source-map-support                ^0.3.2  →          ^0.4.5
 style-loader                     ^0.12.3  →         ^0.13.1

Run ncu with -u to upgrade package.json

**Comment by willsteward** [comment]
Hi @sonicviz was having problems here myself. 

I've not yet managed to solve the problem, but a couple of problems I've uncovered, if it helps guide a fix:

1. The current release uses an old version of shelljs: the "ln" function had problems on Windows in earlier versions.

**Comment by willsteward** [comment]
Hi @sonicviz was having problems here myself.

A few of the problems I've uncovered, if it helps guide a fix:

1. The current release uses an old version of shelljs: the "ln" function had problems on Windows in earlier versions (such as the one defined in the package). Upgrading this to 0.7.4 (or later, depending on when this is read) should fix this (ln is used by dev.js.. I've not checked if there are other instances within the project).
2. Creating symlinks on Windows requires Administrator privileges: so you need to be running your command line with these enabled. I use the PhpStorm IDE's console: I just run PhpStorm in Administrator Mode to overcome this issue.
3. exec() is being run in the meteor directory, here: 

`function runMeteor() {
  cd(dirs.meteor);
  exec('meteor run --settings settings/devel.json', {async: true});
}`

.. but there's no settings/devel.json file available here (if it's meant to be symlinked, that's not working on Windows, even with the fixes above). 

So Meteor then can't find the devel.json file (it's in ../settings/develop.json).

Updating that block in dev.js to:
`function runMeteor() {
  cd(dirs.meteor);
  exec('meteor run --settings ../settings/devel.json', {async: true});
}`

Appears to mean Meteor at least begins to run, but then I get a host of errors: started working through them, and updated to Meteor 1.4 following the upgrade guides (so e.g. you need to rebuild all the node binaries), but it began to become more hassle than it was worth, and I need to mock something up fast (probably just going to use a Linux VM). 

Hope this helps, and would be interested to hear if anyone else has managed to get this running on Windows. I'd go further and try to put together a patch/fix, but can't justify the time required currently to dig deeper into the source: given my understanding of Meteor & Webpack specifically isn't the greatest.
