### ISSUE TITLE
Unable to run an unaltered clone

### ISSUE THREAD

**Issue by dbhandel** [taskandtool/saas-starter#7]
Hi-- 

Your boilerplate looks awesome. I cloned it and tried to start it up but got long list of error messages. I know that I have had an issue with global install of shelljs not being findable by jedwards1211/meteor-webpack-react launch that I haven't been able to solve. Could that be related to these error messages below? If not, is it evident why I'm not succeeding to launch?

Many thanks.

[23:14:47] $ node dev.js
core-js@1.2.6 without ES6 number constructor is up to date
Hash: 6533b4b7ae3df8869325
Version: webpack 1.12.9
Time: 1357ms
               Asset    Size  Chunks             Chunk Names
    server.bundle.js  190 kB       0  [emitted]  main
server.bundle.js.map  237 kB       0  [emitted]  main
chunk    {0} server.bundle.js, server.bundle.js.map (main) 179 kB [rendered]
 70% 1/1 build modulesevents.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:9090
    at Object.exports._errnoException (util.js:860:11)
    at exports._exceptionWithHostPort (util.js:883:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at doNTCallback3 (node.js:461:9)
    at process._tickCallback (node.js:367:17)

[master][davidhandel@DAVIDs-MacBook:~/code/idr-meteor-react]
[23:15:28] 1 $ node dev.js
core-js@1.2.6 without ES6 number constructor is up to date
Hash: 6533b4b7ae3df8869325
Version: webpack 1.12.9
Time: 1434ms
               Asset    Size  Chunks             Chunk Names
    server.bundle.js  190 kB       0  [emitted]  main
server.bundle.js.map  237 kB       0  [emitted]  main
chunk    {0} server.bundle.js, server.bundle.js.map (main) 179 kB [rendered]
 62% 217/249 build modules[[[[[ ~/code/idr-meteor-react/meteor_core ]]]]]

=> Started proxy.
 64% 401/439 build modules=> Started MongoDB.
Hash: a3ba709b40a8fb702436
Version: webpack 1.12.9
Time: 4416ms
           Asset     Size  Chunks             Chunk Names
client.bundle.js  2.92 MB       0  [emitted]  main
chunk    {0} client.bundle.js (main) 2.46 MB [rendered]
webpack: bundle is now VALID.
W20151225-23:16:46.587(-5)? (STDERR)
W20151225-23:16:46.588(-5)? (STDERR) /Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/check/match.js:33
W20151225-23:16:46.588(-5)? (STDERR)     var err = new Match.Error(result.message);
W20151225-23:16:46.588(-5)? (STDERR) ^
W20151225-23:16:46.588(-5)? (STDERR) Error: Match error: Failed Match.Where validation in field region
W20151225-23:16:46.588(-5)? (STDERR)     at check (/Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/check/match.js:33:1)
W20151225-23:16:46.588(-5)? (STDERR)     at new Slingshot.Directive (/Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/edgee_slingshot/packages/edgee_slingshot.js:304:1)
W20151225-23:16:46.589(-5)? (STDERR)     at Object.Slingshot.createDirective (/Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/edgee_slingshot/packages/edgee_slingshot.js:274:1)
W20151225-23:16:46.589(-5)? (STDERR)     at Object.defineProperty.value (/Users/davidhandel/code/idr-meteor-react/webpack/assets/app/lib/ImageUploads.js:2:1)
W20151225-23:16:46.589(-5)? (STDERR)     at __webpack_require__ (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:19:1)
W20151225-23:16:46.589(-5)? (STDERR)     at Object.defineProperty.value (/Users/davidhandel/code/idr-meteor-react/webpack/assets/app/main_server.js:12:41)
W20151225-23:16:46.589(-5)? (STDERR)     at __webpack_require__ (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:19:1)
W20151225-23:16:46.589(-5)? (STDERR)     at Object.installedModules (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:39:1)
W20151225-23:16:46.589(-5)? (STDERR)     at __webpack_require__ (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:19:1)
W20151225-23:16:46.589(-5)? (STDERR)     at /Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:39:1
W20151225-23:16:46.590(-5)? (STDERR)     at Object.<anonymous> (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:39:1)
W20151225-23:16:46.590(-5)? (STDERR)     at Module._compile (module.js:456:26)
W20151225-23:16:46.590(-5)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151225-23:16:46.590(-5)? (STDERR)     at Module.load (module.js:356:32)
W20151225-23:16:46.590(-5)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151225-23:16:46.590(-5)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 1
W20151225-23:16:50.139(-5)? (STDERR)
W20151225-23:16:50.139(-5)? (STDERR) /Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/check/match.js:33
W20151225-23:16:50.139(-5)? (STDERR)     var err = new Match.Error(result.message);
W20151225-23:16:50.140(-5)? (STDERR) ^
W20151225-23:16:50.140(-5)? (STDERR) Error: Match error: Failed Match.Where validation in field region
W20151225-23:16:50.140(-5)? (STDERR)     at check (/Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/check/match.js:33:1)
W20151225-23:16:50.140(-5)? (STDERR)     at new Slingshot.Directive (/Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/edgee_slingshot/packages/edgee_slingshot.js:304:1)
W20151225-23:16:50.140(-5)? (STDERR)     at Object.Slingshot.createDirective (/Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/edgee_slingshot/packages/edgee_slingshot.js:274:1)
W20151225-23:16:50.140(-5)? (STDERR)     at Object.defineProperty.value (/Users/davidhandel/code/idr-meteor-react/webpack/assets/app/lib/ImageUploads.js:2:1)
W20151225-23:16:50.140(-5)? (STDERR)     at __webpack_require__ (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:19:1)
W20151225-23:16:50.140(-5)? (STDERR)     at Object.defineProperty.value (/Users/davidhandel/code/idr-meteor-react/webpack/assets/app/main_server.js:12:41)
W20151225-23:16:50.140(-5)? (STDERR)     at __webpack_require__ (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:19:1)
W20151225-23:16:50.140(-5)? (STDERR)     at Object.installedModules (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:39:1)
W20151225-23:16:50.140(-5)? (STDERR)     at __webpack_require__ (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:19:1)
W20151225-23:16:50.141(-5)? (STDERR)     at /Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:39:1
W20151225-23:16:50.141(-5)? (STDERR)     at Object.<anonymous> (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:39:1)
W20151225-23:16:50.141(-5)? (STDERR)     at Module._compile (module.js:456:26)
W20151225-23:16:50.141(-5)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151225-23:16:50.141(-5)? (STDERR)     at Module.load (module.js:356:32)
W20151225-23:16:50.141(-5)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151225-23:16:50.141(-5)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 1
W20151225-23:16:53.456(-5)? (STDERR)
W20151225-23:16:53.457(-5)? (STDERR) /Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/check/match.js:33
W20151225-23:16:53.457(-5)? (STDERR)     var err = new Match.Error(result.message);
W20151225-23:16:53.457(-5)? (STDERR) ^
W20151225-23:16:53.457(-5)? (STDERR) Error: Match error: Failed Match.Where validation in field region
W20151225-23:16:53.457(-5)? (STDERR)     at check (/Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/check/match.js:33:1)
W20151225-23:16:53.457(-5)? (STDERR)     at new Slingshot.Directive (/Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/edgee_slingshot/packages/edgee_slingshot.js:304:1)
W20151225-23:16:53.457(-5)? (STDERR)     at Object.Slingshot.createDirective (/Users/davidhandel/code/idr-meteor-react/meteor_core/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/edgee_slingshot/packages/edgee_slingshot.js:274:1)
W20151225-23:16:53.457(-5)? (STDERR)     at Object.defineProperty.value (/Users/davidhandel/code/idr-meteor-react/webpack/assets/app/lib/ImageUploads.js:2:1)
W20151225-23:16:53.457(-5)? (STDERR)     at __webpack_require__ (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:19:1)
W20151225-23:16:53.457(-5)? (STDERR)     at Object.defineProperty.value (/Users/davidhandel/code/idr-meteor-react/webpack/assets/app/main_server.js:12:41)
W20151225-23:16:53.458(-5)? (STDERR)     at __webpack_require__ (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:19:1)
W20151225-23:16:53.458(-5)? (STDERR)     at Object.installedModules (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:39:1)
W20151225-23:16:53.458(-5)? (STDERR)     at __webpack_require__ (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:19:1)
W20151225-23:16:53.458(-5)? (STDERR)     at /Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:39:1
W20151225-23:16:53.458(-5)? (STDERR)     at Object.<anonymous> (/Users/davidhandel/code/idr-meteor-react/webpack/assets/webpack:/webpack/bootstrap 6533b4b7ae3df8869325:39:1)
W20151225-23:16:53.458(-5)? (STDERR)     at Module._compile (module.js:456:26)
W20151225-23:16:53.458(-5)? (STDERR)     at Object.Module._extensions..js (module.js:474:10)
W20151225-23:16:53.458(-5)? (STDERR)     at Module.load (module.js:356:32)
W20151225-23:16:53.459(-5)? (STDERR)     at Function.Module._load (module.js:312:12)
W20151225-23:16:53.459(-5)? (STDERR)     at Module.require (module.js:364:17)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by gdub01** [comment]
Hey David - Sorry about that.

It looks like it's something with the Amazon s3 uploader run by
Edgee:slingshot meteor package. I've messed with the settings a bit and how
it works sort of depends on how you have it setup on Amazon.

In app/lib/imageuploads.js can you try removing lines 4 and 30? It allows
you to set a bucket region, but I think it defaults to US East fine without
it and it helped me.

If that doesn't work, can you let me know?

Thanks

**Comment by dbhandel** [comment]
Thanks Gavin! That did the trick. I can't wait to play with this.
